common:
        loglevel: debug

        boto_bucket: docker-registry

        # Amazon S3 Storage Configuration
        s3_access_key: XXX
        s3_secret_key: XXX
        s3_bucket: docker-registry
        s3_encrypt: true
        s3_secure: true

        secret_key: 013e6e301d6e597a1281d88662ff4a09b4fc59bf3d710375ea2ef8f8874ca134

prod:
        storage: s3
        storage_path: /prod

local:
        storage: local
        storage_path: /docker-registry-storage
